server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /lpor/api/ {
        proxy_pass http://lpor-api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /lpor/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
